#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#Convert MultiRegion Fluent Mesh
dos2unix OF_4in_5a5mm_50KMesh.msh
runApplication fluentMeshToFoam -writeZones OF_4in_5a5mm_50KMesh.msh
runApplication splitMeshRegions -cellZones -overwrite
restore0Dir
runApplication checkMesh -allGeometry

# Create ignition source cells
runApplication topoSet -region fluid_0

# Create Parafoam files
touch Results.foam
#paraFoam -region fluid_0 -touch
#paraFoam -region solid_1 -touch
#paraFoam -region solid_2 -touch

#runApplication potentialFoam

#------------------------------------------------------------------------------
