#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial run functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf VTK
rm -rf constant/cellToRegion
rm -rf constant/*/polyMesh 0/cellToRegion 0/*/cellToRegion
rm -rf log.*

#------------------------------------------------------------------------------
