#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial run functions
#------------------------------------------------------------------------------

cleanCase0

#rm -rf VTK
#rm -rf constant/cellToRegion
#rm -rf constant/*/polyMesh 0/cellToRegion 0/*/cellToRegion

rm -rf log.*
rm -rf log.chtMultiRegionFoam
rm -rf log.decomposePar
rm -rf logs.old
rm -rf Results.foam
rm -rf postProcessing
rm -rf 0
rm -rf processor0
rm -rf processor1
rm -rf processor2
rm -rf processor3

#------------------------------------------------------------------------------
